language: go
go:
  - 1.4
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - echo "pass"
script:
  - go test -v ./...
after_success:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/codeskyblue/gorelease/master/scripts/build-standalone.sh)" args0 "windows linux darwin"
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/codeskyblue/gorelease/master/scripts/upload-qiniu.sh)"
